//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Demo.Properties.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 AutoRun 的本地化字符串。
        /// </summary>
        public static string AutoRun {
            get {
                return ResourceManager.GetString("AutoRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom 的本地化字符串。
        /// </summary>
        public static string custom {
            get {
                return ResourceManager.GetString("custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exter. 的本地化字符串。
        /// </summary>
        public static string exter {
            get {
                return ResourceManager.GetString("exter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inter. 的本地化字符串。
        /// </summary>
        public static string inter {
            get {
                return ResourceManager.GetString("inter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manual 的本地化字符串。
        /// </summary>
        public static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Position 的本地化字符串。
        /// </summary>
        public static string pos {
            get {
                return ResourceManager.GetString("pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setpoint 的本地化字符串。
        /// </summary>
        public static string sp {
            get {
                return ResourceManager.GetString("sp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Speed 的本地化字符串。
        /// </summary>
        public static string spd {
            get {
                return ResourceManager.GetString("spd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 aaa 的本地化字符串。
        /// </summary>
        public static string TestName {
            get {
                return ResourceManager.GetString("TestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zone1 的本地化字符串。
        /// </summary>
        public static string zone1 {
            get {
                return ResourceManager.GetString("zone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zone2 的本地化字符串。
        /// </summary>
        public static string zone2 {
            get {
                return ResourceManager.GetString("zone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zone3 的本地化字符串。
        /// </summary>
        public static string zone3 {
            get {
                return ResourceManager.GetString("zone3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zone4 的本地化字符串。
        /// </summary>
        public static string zone4 {
            get {
                return ResourceManager.GetString("zone4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zone5 的本地化字符串。
        /// </summary>
        public static string zone5 {
            get {
                return ResourceManager.GetString("zone5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zone6 的本地化字符串。
        /// </summary>
        public static string zone6 {
            get {
                return ResourceManager.GetString("zone6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zone7 的本地化字符串。
        /// </summary>
        public static string zone7 {
            get {
                return ResourceManager.GetString("zone7", resourceCulture);
            }
        }
    }
}
